development:
  domain: localhost
  auth: http://localhost:3000
  qb: http://localhost:3001
  store: http://localhost:3002
  studyegg: http://localhost:3003

test:
  domain: localhost
  auth: http://localhost:3000
  qb: http://localhost:3001
  store: http://localhost:3002
  studyegg: http://localhost:3003

production:
  domain: .zendolabs.com
  auth: http://zendolabs.com
  qb: http://questionbase.zendolabs.com
  store: http://store.zendolabs.com
  studyegg: http://www.zendolabs.com
